---

- hosts: all
  become: true
  tasks:

    - name: sudo apt update
      apt:
        update_cache: yes

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
