---

- hosts: all
  become: true
  tasks:

    - name: update and install packages
      package:
        update_cache: yes
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest


