---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

    - name: install apache and php
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: db_server
  become: true
  tasks: 

    - name: installing mariadb
      apt: 
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

