---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base

- hosts: web_server
  become: true
  roles: 
    - web_server

- hosts: db_server
  become: true
  roles: 
    - db_server
