---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

    - name: install apache and php
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy default html file for site
      tags: apache,apache2,ubuntu
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_server
  become: true
  tasks: 

    - name: installing mariadb
      tags: db,mariadb,ubuntu
      apt: 
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

