- name: add ssh key for chxnedu
  tags: always
  authorized_key: 
     user: chxnedu
     key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjwQvzQtrvP0iDua5SSqQlNaO6q3tTdZ3TS8hoDcUrJNnDjy+IOCeA2a7Bzioyu+O0cTB2CFCiOEAhdfIqMfZQCRkFtu7h1efgusG6xrGUSYnP++V+xd7bu/y5eyeFKQoThCPTp0Q9uDz8BNEw5vyLd9yvdm7RMfxIQIGjVYMV7FSJPpnFb8qNAhqW7Ex8ZB8eWMXdhBN0LAMZYx521/zPZK0z3zAPAOoJagVZgqbWr4qkLpYAeI3nnGbsBBJWO0XVMp2mk4JPxLdjbrHCL3/ix5MlVenFYMeZxZw2e/9ngWQcnS+OAYHJ44JUWf/G9EQ9AekoNmb/8Rxn9jY1cqUnvztGroLsL7kHdlImdIs4EMG1MNS47SpkJoD5BjZzOaX966r93hKNck2GOlcOYt3tuTKqtwHNLHfMecCIqJXNq5h2UrV1Vazp1ExBpDKsv6hmILXXKnjKZb7LmUtAI5i8avkii+0kszGkEcNZyzt1UthyjKQrDaoJkgZbWrmUODk= ubuntu@ip-172-31-22-81"
